services:
  db:
    image: postgres:15-alpine
    container_name: postgres-db
    #restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    #volumes:
    #- pgdata:/var/lib/postgresql/data
#volumes:
#pgdata:
#driver: local
