spring:
  config:
    import: "optional:file:./.env[.properties]"
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  mvc:
    trailing-slash-match: true

  sql:
    init:
      mode: always # runs a sql script if available
      platform: postgres

server:
  port: ${SERVER_PORT}

management:
  endpoints:
    web:
      exposure:
        include: health # check on endpoint /actuator/health

  health:
    db:
      enabled: true
    defaults:
      enabled: true

springdoc:
  swagger-ui:
    url: /swagger/swagger.yml
    disable-swagger-default-url: true

---
spring:
  autoconfigure:
    exclude:
      - org.springdoc.webmvc.core.configuration.SpringDocWebMvcConfiguration
      - org.springdoc.webmvc.core.configuration.MultipleOpenApiSupportConfiguration
      - org.springframework.boot.actuate.autoconfigure.web.server.ManagementContextAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.endpoint.web.WebEndpointAutoConfiguration
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:tc:postgresql:15:${DB_TESTNAME}
    username: ${DB_TESTUSER}
    password: ${DB_TESTPASSWORD}
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  sql:
    init:
      mode: always

  springdoc:
    enabled: false # Disable Swagger during tests

  management:
    endpoints:
      web:
        exposure:
          include: none # Disable Actuator endpoints during tests
  health:
    db:
      enabled: false
    defaults:
      enabled: false
