spring:
  config:
    import: "optional:file:./.env[.properties]"
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  mvc:
    trailing-slash-match: true
server:
  port: ${SERVER_PORT}
management:
  endpoints:
    web:
      exposure:
        include: health
  health:
    db:
      enabled: true
    defaults:
      enabled: true
springdoc:
  swagger-ui:
    url: /swagger/swagger.yml
    disable-swagger-default-url: true

---
spring:
  config:
    activate:
      on-profile: test
  autoconfigure:
    exclude:
      - org.springdoc.webmvc.core.configuration.SpringDocWebMvcConfiguration
      - org.springdoc.webmvc.core.configuration.MultipleOpenApiSupportConfiguration
  datasource:
    url: jdbc:tc:postgresql:15:${DB_TESTNAME}
    username: ${DB_TESTUSER}
    password: ${DB_TESTPASSWORD}
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  sql:
    init:
      mode: always
springdoc:
  enabled: false
management:
  endpoints:
    web:
      exposure:
        include: none
  health:
    db:
      enabled: false
    defaults:
      enabled: false

